// Generated by Skyramp v1.3.13 on 2026-03-16 21:13:59.97644905 +0000 UTC m=+128.318950109
// Command: skyramp generate fuzz rest http://localhost:8055/archive/archive_test_articles \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"keys":[1],"status_field":"status"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// fuzz test for /archive/archive_test_articles PATCH
test('testArchiveTestArticlesPatch', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const archiveTestArticlesPatchRequestBody = `{
            "keys": [
                1
            ],
            "status_field": "status"
        }`
    
    // Fuzz strategies
    const archiveTestArticlesPatchFuzzedBody = {
        "keys": [-10],
        "status_field": "0123456789"
    };
    // Fuzz status codes
    const expectedArchiveTestArticlesPatchStatusCode: Record<string, string> = {
        "keys": ["40x"],
        "status_field": "40x"
    };
    // Fuzz status codes for Null values
    const expectedArchiveTestArticlesPatchNullStatusCode: Record<string, string> = {
        "keys": ["40x"],
        "status_field": "40x"
    };

    // Execute Request
    let archiveTestArticlesPatchResponse = await client.sendRequest({
        url:URL,
        path:"/archive/archive_test_articles",
        method:"PATCH",
        body:archiveTestArticlesPatchRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(archiveTestArticlesPatchFuzzedBody)) {
        // Execute Request
        archiveTestArticlesPatchResponse = await client.sendRequest({
            url:URL,
            path:"/archive/archive_test_articles",
            method:"PATCH",
            body:archiveTestArticlesPatchRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(archiveTestArticlesPatchFuzzedBody, key)},
            expectedCode:getValue(expectedArchiveTestArticlesPatchStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(archiveTestArticlesPatchFuzzedBody, key)}`
        });


        // Execute Request
        archiveTestArticlesPatchResponse = await client.sendRequest({
            url:URL,
            path:"/archive/archive_test_articles",
            method:"PATCH",
            body:archiveTestArticlesPatchRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedArchiveTestArticlesPatchNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

