// Generated by Skyramp v1.3.13 on 2026-03-19 21:47:24.639366161 +0000 UTC m=+120.253919029
// Command: skyramp generate contract rest http://localhost:8055/status \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_status.spec.ts \
// 		--output-dir /home/runner/work/directus-roshinimichael/directus-roshinimichael/tests \
// 		--overwrite \
// 		--provider \
// 		--response-data {"data":{"uptime":1234.56,"timestamp":"2026-03-19T00:00:00.000Z","status":"healthy","version":"1.0.0","environment":"development"}} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /status GET
test('testStatusGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedStatusGetResponseBody: string = `{
        "data": {
            "environment": "development",
            "status": "healthy",
            "timestamp": "2026-03-19T00:00:00.000Z",
            "uptime": 1234.56,
            "version": "1.0.0"
        }
    }`;

    // Execute Request
    const statusGetResponse = await client.sendRequest({
        url: URL,
        path: "/status",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(statusGetResponse, "20x"), 'status code').toBeTruthy();
    expect(checkSchema(statusGetResponse, expectedStatusGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(statusGetResponse, "data.environment"), 'value').not.toBeNull();
    expect(getResponseValue(statusGetResponse, "data.status"), 'value').not.toBeNull();
    expect(getResponseValue(statusGetResponse, "data.timestamp"), 'value').not.toBeNull();
});
