// Generated by Skyramp v1.3.13 on 2026-03-19 21:47:26.822156433 +0000 UTC m=+122.436709311
// Command: skyramp generate contract rest http://localhost:8055/status/database \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_status_component.spec.ts \
// 		--output-dir /home/runner/work/directus-roshinimichael/directus-roshinimichael/tests \
// 		--overwrite \
// 		--provider \
// 		--response-data {"data":{"component":"database","status":"operational","checked_at":"2026-03-19T00:00:00.000Z","response_time":42}} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /status/database GET
test('testDatabaseGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedDatabaseGetResponseBody: string = `{
        "data": {
            "checked_at": "2026-03-19T00:00:00.000Z",
            "component": "database",
            "response_time": 42,
            "status": "operational"
        }
    }`;

    // Execute Request
    const databaseGetResponse = await client.sendRequest({
        url: URL,
        path: "/status/database",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(databaseGetResponse, "20x"), 'status code').toBeTruthy();
    expect(checkSchema(databaseGetResponse, expectedDatabaseGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(databaseGetResponse, "data.checked_at"), 'value').not.toBeNull();
    expect(getResponseValue(databaseGetResponse, "data.component"), 'value').not.toBeNull();
    expect(getResponseValue(databaseGetResponse, "data.response_time"), 'value').not.toBeNull();
});
