// Generated by Skyramp v1.3.13 on 2026-03-18 14:20:04.019925463 +0000 UTC m=+146.050544616
// Command: skyramp generate fuzz rest http://localhost:8055/exports/test_exports_json \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output exports-fuzz.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"format":"json","fields":["id","title"]} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// fuzz test for /exports/test_exports_json POST
test('testTestExportsJsonPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const testExportsJsonPostRequestBody = `{
            "format": "json",
            "fields": [
                "id",
                "title"
            ]
        }`
    
    // Fuzz strategies
    const testExportsJsonPostFuzzedBody = {
        "fields": [
            "0123456789",
                "0123456789"
        ],
        "format": "0123456789"
    };
    // Fuzz status codes
    const expectedTestExportsJsonPostStatusCode: Record<string, string> = {
        "fields": [
            "40x",
                "40x"
        ],
        "format": "40x"
    };
    // Fuzz status codes for Null values
    const expectedTestExportsJsonPostNullStatusCode: Record<string, string> = {
        "fields": [
            "40x",
                "40x"
        ],
        "format": "40x"
    };

    // Execute Request
    let testExportsJsonPostResponse = await client.sendRequest({
        url:URL,
        path:"/exports/test_exports_json",
        method:"POST",
        body:testExportsJsonPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(testExportsJsonPostFuzzedBody)) {
        // Execute Request
        testExportsJsonPostResponse = await client.sendRequest({
            url:URL,
            path:"/exports/test_exports_json",
            method:"POST",
            body:testExportsJsonPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(testExportsJsonPostFuzzedBody, key)},
            expectedCode:getValue(expectedTestExportsJsonPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(testExportsJsonPostFuzzedBody, key)}`
        });


        // Execute Request
        testExportsJsonPostResponse = await client.sendRequest({
            url:URL,
            path:"/exports/test_exports_json",
            method:"POST",
            body:testExportsJsonPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedTestExportsJsonPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

