// Generated by Skyramp v1.3.13 on 2026-03-18 14:20:06.485687571 +0000 UTC m=+148.516306724
// Command: skyramp generate contract rest http://localhost:8055/exports/test_exports_json \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output exports-contract.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"format":"json"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /exports/test_exports_json POST
test('testTestExportsJsonPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const testExportsJsonPostRequestBody: string = `{
        "format": "json"
    }`;

    // Execute Request
    const testExportsJsonPostResponse = await client.sendRequest({
        url: URL,
        path: "/exports/test_exports_json",
        method: "POST",
        body: testExportsJsonPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(testExportsJsonPostResponse, "20x"), 'status code').toBeTruthy();
});
