// Generated by Skyramp v1.3.13 on 2026-03-19 21:47:28.742438648 +0000 UTC m=+124.356991496
// Command: skyramp generate fuzz rest http://localhost:8055/status/database \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output fuzz_status_component.spec.ts \
// 		--output-dir /home/runner/work/directus-roshinimichael/directus-roshinimichael/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// fuzz test for /status/database GET
test('testDatabaseGet', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    let databaseGetResponse = await client.sendRequest({
        url:URL,
        path:"/status/database",
        method:"GET",
        headers:headers,
        expectedCode:"20x"
    });


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

