// Generated by Skyramp v1.3.13 on 2026-03-18 14:31:06.224077167 +0000 UTC m=+136.775590848
// Command: skyramp generate fuzz rest http://localhost:8055/archive/test_archive_collection \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output fuzz_archive_collection.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"keys":[1],"status_field":"status"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// fuzz test for /archive/test_archive_collection PATCH
test('testTestArchiveCollectionPatch', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const testArchiveCollectionPatchRequestBody = `{
            "keys": [
                1
            ],
            "status_field": "status"
        }`
    
    // Fuzz strategies
    const testArchiveCollectionPatchFuzzedBody = {
        "keys": [-10],
        "status_field": "0123456789"
    };
    // Fuzz status codes
    const expectedTestArchiveCollectionPatchStatusCode: Record<string, string> = {
        "keys": ["40x"],
        "status_field": "40x"
    };
    // Fuzz status codes for Null values
    const expectedTestArchiveCollectionPatchNullStatusCode: Record<string, string> = {
        "keys": ["40x"],
        "status_field": "40x"
    };

    // Execute Request
    let testArchiveCollectionPatchResponse = await client.sendRequest({
        url:URL,
        path:"/archive/test_archive_collection",
        method:"PATCH",
        body:testArchiveCollectionPatchRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(testArchiveCollectionPatchFuzzedBody)) {
        // Execute Request
        testArchiveCollectionPatchResponse = await client.sendRequest({
            url:URL,
            path:"/archive/test_archive_collection",
            method:"PATCH",
            body:testArchiveCollectionPatchRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(testArchiveCollectionPatchFuzzedBody, key)},
            expectedCode:getValue(expectedTestArchiveCollectionPatchStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(testArchiveCollectionPatchFuzzedBody, key)}`
        });


        // Execute Request
        testArchiveCollectionPatchResponse = await client.sendRequest({
            url:URL,
            path:"/archive/test_archive_collection",
            method:"PATCH",
            body:testArchiveCollectionPatchRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedTestArchiveCollectionPatchNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

