// Generated by Skyramp v1.3.13 on 2026-03-19 21:47:38.479342913 +0000 UTC m=+134.093895771
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_status_health.spec.ts \
// 		--output-dir /home/runner/work/directus-roshinimichael/directus-roshinimichael/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/directus-roshinimichael/directus-roshinimichael/tests/scenario_status-system-health-check.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    let statusGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/status",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(statusGetResponse.statusCode, 'status code').toBe(200);
});

