// Generated by Skyramp v1.3.13 on 2026-03-16 18:39:40.939538621 +0000 UTC m=+319.562358365
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output math_add_integration_test.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/directus/directus/tests/scenario_math-add-qp-validation.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    let addGetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/math/add",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(addGetResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let addGet1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/math/add",
        method:"GET",
        headers:headers
    });

    // Generated Assertions
    expect(addGet1Response.statusCode, 'status code').toBe(200);
});

