// Generated by Skyramp v1.3.13 on 2026-03-16 20:39:01.772131857 +0000 UTC m=+207.592453733
// Command: skyramp generate e2e rest \
// 		--docker-network directus_default \
// 		--framework playwright \
// 		--language typescript \
// 		--output server_info_e2e_test.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/directus/directus/skyramp_playwright.zip \
// 		--provider \
// 		--runtime docker \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/directus/directus/skyramp_traces.json

// Import of required libraries
import { test } from '@playwright/test';
import { getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test('testE2E', async ({ page }) => {
    test.setTimeout(171000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080/admin/login");
    await page.getByRole("textbox", { name: "Email" }).click();

    const playwrightRequest0: Record<string, any> = {
        "email": "admin@example.com",
        "password": "admin"
    };

    await page.getByRole("textbox", { name: "Email" }).fill(getValue(playwrightRequest0, "email"));
    await page.getByRole("textbox", { name: "Password" }).click();
    await page.getByRole("textbox", { name: "Password" }).fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/auth/login**");
    await page.getByRole("button", { name: "Sign In" }).click();
    const response0 = await responsePromise0;

    await page.getByRole("link", { name: "dns" }).click();
    await page.getByRole("link", { name: "dns" }).click();
    await page.getByRole("link").nth(3).click();
    await page.getByRole("link", { name: "dns" }).click();
    await page.getByText("Healthy").click();
    await page.goto("http://localhost:8080/admin/server-info");
});
