// Generated by Skyramp v1.3.13 on 2026-03-16 18:28:36.41544264 +0000 UTC m=+109.902907539
// Command: skyramp generate contract rest http://localhost:8055/server/info \
// 		--docker-network directus_default \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output server_info_contract_test.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime docker \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /server/info GET
test('testInfoGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient({
        runtime: "docker",
        dockerNetwork: "directus_default",
        dockerSkyrampPort: 35142
    });
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const infoGetResponse = await client.sendRequest({
        url: URL,
        path: "/server/info",
        method: "GET",
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(infoGetResponse, "20x"), 'status code').toBeTruthy();
});
