// Generated by Skyramp v1.3.13 on 2026-03-16 22:42:24.015560599 +0000 UTC m=+153.136848962
// Command: skyramp generate contract rest http://localhost:8055/utils/random/string \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output utils_random_string_charset_contract.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--query-params charset=hex,length=16 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /utils/random/string GET
test('testStringGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Execute Request
    const stringGetResponse = await client.sendRequest({
        url: URL,
        path: "/utils/random/string",
        method: "GET",
        headers: headers,
        queryParams: {
            "charset": "hex",
            "length": "16"
        }
    });

    // Generated Assertions
    expect(checkStatusCode(stringGetResponse, "20x"), 'status code').toBeTruthy();
});
