// Generated by Skyramp v1.3.13 on 2026-03-16 22:42:24.265054847 +0000 UTC m=+153.386343211
// Command: skyramp generate contract rest http://localhost:8055/utils/hash/verify \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output utils_hash_verify_sha512_contract.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"string":"directus-test-secret-2025","hash":"a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3","algorithm":"sha512"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// contract test for /utils/hash/verify POST
test('testVerifyPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const verifyPostRequestBody: string = `{
        "algorithm": "sha512",
        "hash": "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
        "string": "directus-test-secret-2025"
    }`;

    // Execute Request
    const verifyPostResponse = await client.sendRequest({
        url: URL,
        path: "/utils/hash/verify",
        method: "POST",
        body: verifyPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(verifyPostResponse, "20x"), 'status code').toBeTruthy();
});
