// Generated by Skyramp v1.3.13 on 2026-03-16 22:42:24.09215424 +0000 UTC m=+153.213442614
// Command: skyramp generate fuzz rest http://localhost:8055/utils/hash/generate \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output utils_hash_generate_algorithm_fuzz.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--request-data {"string":"test-input","algorithm":"sha256"} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

// fuzz test for /utils/hash/generate POST
test('testGeneratePost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const generatePostRequestBody = `{
            "string": "test-input",
            "algorithm": "sha256"
        }`
    
    // Fuzz strategies
    const generatePostFuzzedBody = {
        "algorithm": "0123456789",
        "string": "0123456789"
    };
    // Fuzz status codes
    const expectedGeneratePostStatusCode: Record<string, string> = {
        "algorithm": "40x",
        "string": "40x"
    };
    // Fuzz status codes for Null values
    const expectedGeneratePostNullStatusCode: Record<string, string> = {
        "algorithm": "40x",
        "string": "40x"
    };

    // Execute Request
    let generatePostResponse = await client.sendRequest({
        url:URL,
        path:"/utils/hash/generate",
        method:"POST",
        body:generatePostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(generatePostFuzzedBody)) {
        // Execute Request
        generatePostResponse = await client.sendRequest({
            url:URL,
            path:"/utils/hash/generate",
            method:"POST",
            body:generatePostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(generatePostFuzzedBody, key)},
            expectedCode:getValue(expectedGeneratePostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(generatePostFuzzedBody, key)}`
        });


        // Execute Request
        generatePostResponse = await client.sendRequest({
            url:URL,
            path:"/utils/hash/generate",
            method:"POST",
            body:generatePostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedGeneratePostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

