// Generated by Skyramp v1.3.13 on 2026-03-16 22:41:47.100363004 +0000 UTC m=+116.221651368
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output utils_hash_sha256_generate_verify.spec.ts \
// 		--output-dir /home/runner/work/directus/directus/tests \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/directus/directus/tests/scenario_utils-hash-sha256-generate-verify.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8055");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const generatePostRequestBody = `{
            "algorithm": "sha256",
            "string": "directus-test-secret-2025"
        }`
    
    // Execute Request
    let generatePostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/hash/generate",
        method:"POST",
        body:generatePostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(generatePostResponse.statusCode, 'status code').toBe(200);

    // Request Body — hash chained from generate response
    const generatedHash = getValue(generatePostResponse, "data");
    const verifyPostRequestBody = JSON.stringify({
            "algorithm": "sha256",
            "hash": generatedHash,
            "string": "directus-test-secret-2025"
        })
    
    // Execute Request
    let verifyPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/utils/hash/verify",
        method:"POST",
        body:verifyPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(verifyPostResponse.statusCode, 'status code').toBe(200);
});

